name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What did you expect vs what actually happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Run `/app-store-toolkit:push`
        2. ...
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Node version, OS, Claude Code version"
      placeholder: "Node 20, macOS 15, Claude Code 1.x"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      render: shell
    validations:
      required: false
